server.port: 8080
spring:
  profiles.active: dev
  application.name: saleass
---

spring:
  profiles: dev
  h2.console:
    enabled: true
    path: /h2
---

spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db/saleass?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: root
    password: rootp
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop
server.port: 80
